"""Default-kategorier och basregler för kategorisering.

Alla kategori-namn här MÅSTE komma från `canonical.CANONICAL_CATEGORIES`.
Tidigare hade vi en parent/child-trädstruktur (Mat → Livsmedel/Restaurang),
vilket krockade med Budget-vyns platta lista (Konsumentverket-schablon).
Nu en enda platt lista som matchar Budget-verktyget exakt.

Aliases (gamla namn) hanteras av canonical.canonicalize() vid läsning
och av db/migrate.py vid uppgradering av befintliga rader.
"""
from .canonical import (
    CANONICAL_CATEGORIES,
    CAT_BOENDE,
    CAT_HUSHALLSEL,
    CAT_INTERNET_MOBIL,
    CAT_STROMNINGSTJANSTER,
    CAT_FORSAKRING,
    CAT_LAN,
    CAT_MAT_LIVSMEDEL,
    CAT_RESTAURANG,
    CAT_KLADER_SKOR,
    CAT_HALSA_HYGIEN,
    CAT_NOJE_FRITID,
    CAT_HEMUTRUSTNING,
    CAT_FORBRUKNINGSVAROR,
    CAT_TRANSPORT,
    CAT_SPARMAL,
    CAT_PENSION,
    CAT_LON,
    CAT_SKATTEATERBARING,
    CAT_OVRIG_INKOMST,
    CAT_OVRIGT,
)


# === Default-kategorier (platt · ingen parent-tree) ===
# Format: (name, parent_name, icon). parent_name BEHÅLLS i schemat
# (Category.parent_id FK) men sätts ALLTID till None för dessa kanoniska
# rader så hela listan är platt.
DEFAULT_CATEGORIES: list[tuple[str, str | None, str | None]] = [
    # Inkomst
    (CAT_LON, None, "arrow-down"),
    (CAT_SKATTEATERBARING, None, "arrow-down"),
    (CAT_OVRIG_INKOMST, None, "arrow-down"),
    # Fasta utgifter
    (CAT_BOENDE, None, "home"),
    (CAT_HUSHALLSEL, None, "zap"),
    (CAT_INTERNET_MOBIL, None, "wifi"),
    (CAT_STROMNINGSTJANSTER, None, "play"),
    (CAT_FORSAKRING, None, "shield"),
    (CAT_LAN, None, "trending-down"),
    # Rörliga utgifter
    (CAT_MAT_LIVSMEDEL, None, "shopping-cart"),
    (CAT_RESTAURANG, None, "coffee"),
    (CAT_KLADER_SKOR, None, "shirt"),
    (CAT_HALSA_HYGIEN, None, "heart"),
    (CAT_NOJE_FRITID, None, "film"),
    (CAT_HEMUTRUSTNING, None, "package"),
    (CAT_FORBRUKNINGSVAROR, None, "box"),
    (CAT_TRANSPORT, None, "car"),
    # Sparande
    (CAT_SPARMAL, None, "trending-up"),
    (CAT_PENSION, None, "calendar"),
    # Fallback
    (CAT_OVRIGT, None, "help-circle"),
]


# === Seed-regler · pattern → kanonisk kategori ===
# Alla kategori-namn här MÅSTE finnas i CANONICAL_CATEGORIES.
SEED_RULES: list[tuple[str, str, int]] = [
    # Livsmedel
    ("ica", CAT_MAT_LIVSMEDEL, 100),
    ("coop", CAT_MAT_LIVSMEDEL, 100),
    ("willys", CAT_MAT_LIVSMEDEL, 100),
    ("lidl", CAT_MAT_LIVSMEDEL, 100),
    ("hemköp", CAT_MAT_LIVSMEDEL, 100),
    ("city gross", CAT_MAT_LIVSMEDEL, 100),
    ("mathem", CAT_MAT_LIVSMEDEL, 100),
    ("hjogotten", CAT_MAT_LIVSMEDEL, 100),
    ("broderna brandt", CAT_MAT_LIVSMEDEL, 100),
    ("bröderna brandt", CAT_MAT_LIVSMEDEL, 100),
    ("vete & rag", CAT_MAT_LIVSMEDEL, 100),
    ("tempo", CAT_MAT_LIVSMEDEL, 100),
    ("damaskus", CAT_MAT_LIVSMEDEL, 100),
    ("minilivs", CAT_MAT_LIVSMEDEL, 90),
    ("minibutik", CAT_MAT_LIVSMEDEL, 90),
    ("livs ", CAT_MAT_LIVSMEDEL, 70),
    ("systembolag", CAT_MAT_LIVSMEDEL, 100),
    # Restaurang & café
    ("mcdonald", CAT_RESTAURANG, 100),
    ("max ", CAT_RESTAURANG, 100),
    ("burger king", CAT_RESTAURANG, 100),
    ("sushi", CAT_RESTAURANG, 100),
    ("pizza", CAT_RESTAURANG, 100),
    ("espresso house", CAT_RESTAURANG, 100),
    ("waynes coffee", CAT_RESTAURANG, 100),
    ("wayne's coffee", CAT_RESTAURANG, 100),
    ("starbucks", CAT_RESTAURANG, 100),
    ("pizzeria", CAT_RESTAURANG, 70),
    ("restaurang", CAT_RESTAURANG, 60),
    (" rest ", CAT_RESTAURANG, 50),
    ("café ", CAT_RESTAURANG, 60),
    ("cafeet", CAT_RESTAURANG, 60),
    ("pinchos", CAT_RESTAURANG, 100),
    ("brane", CAT_RESTAURANG, 80),
    ("bran's", CAT_RESTAURANG, 100),
    ("go banana", CAT_RESTAURANG, 100),
    ("lantkrog", CAT_RESTAURANG, 100),
    # Kläder & skor
    ("h&m", CAT_KLADER_SKOR, 100),
    ("zara", CAT_KLADER_SKOR, 100),
    ("lindex", CAT_KLADER_SKOR, 100),
    ("kappahl", CAT_KLADER_SKOR, 100),
    ("åhléns", CAT_KLADER_SKOR, 100),
    ("ahlens", CAT_KLADER_SKOR, 100),
    ("gina tricot", CAT_KLADER_SKOR, 100),
    ("lager 157", CAT_KLADER_SKOR, 100),
    ("cubus", CAT_KLADER_SKOR, 100),
    ("kids brand", CAT_KLADER_SKOR, 100),
    ("dressmann", CAT_KLADER_SKOR, 100),
    ("jack & jones", CAT_KLADER_SKOR, 100),
    ("vero moda", CAT_KLADER_SKOR, 100),
    ("peak performance", CAT_KLADER_SKOR, 100),
    ("stadium", CAT_KLADER_SKOR, 100),
    ("babyshop", CAT_KLADER_SKOR, 100),
    # Boende
    ("hyra", CAT_BOENDE, 100),
    ("brf ", CAT_BOENDE, 90),
    ("hsb ", CAT_BOENDE, 90),
    ("avgift bostad", CAT_BOENDE, 100),
    ("bolåneränta", CAT_BOENDE, 100),
    ("amortering", CAT_BOENDE, 100),
    # Hushållsel
    ("telinet", CAT_HUSHALLSEL, 100),
    ("hjo energi", CAT_HUSHALLSEL, 100),
    ("göteborg energi", CAT_HUSHALLSEL, 100),
    ("tibber", CAT_HUSHALLSEL, 100),
    ("vattenfall", CAT_HUSHALLSEL, 100),
    ("fortum", CAT_HUSHALLSEL, 100),
    # Internet & mobil
    ("telia", CAT_INTERNET_MOBIL, 100),
    ("tele2", CAT_INTERNET_MOBIL, 100),
    ("comhem", CAT_INTERNET_MOBIL, 100),
    ("bahnhof", CAT_INTERNET_MOBIL, 100),
    ("hallon", CAT_INTERNET_MOBIL, 100),
    ("tre.se", CAT_INTERNET_MOBIL, 100),
    # Strömningstjänster
    ("netflix", CAT_STROMNINGSTJANSTER, 100),
    ("hbo", CAT_STROMNINGSTJANSTER, 100),
    ("spotify", CAT_STROMNINGSTJANSTER, 100),
    ("disney", CAT_STROMNINGSTJANSTER, 100),
    ("viaplay", CAT_STROMNINGSTJANSTER, 100),
    ("storytel", CAT_STROMNINGSTJANSTER, 100),
    ("nextory", CAT_STROMNINGSTJANSTER, 100),
    ("tidal", CAT_STROMNINGSTJANSTER, 100),
    ("tv4", CAT_STROMNINGSTJANSTER, 90),
    ("openai", CAT_STROMNINGSTJANSTER, 100),
    ("chatgpt", CAT_STROMNINGSTJANSTER, 100),
    ("cursor", CAT_STROMNINGSTJANSTER, 100),
    ("perplexity", CAT_STROMNINGSTJANSTER, 100),
    ("anthropic", CAT_STROMNINGSTJANSTER, 100),
    # Försäkring (samtliga)
    ("folksam", CAT_FORSAKRING, 100),
    ("trygg-hansa", CAT_FORSAKRING, 100),
    ("if försäkring", CAT_FORSAKRING, 100),
    ("länsförsäkringar", CAT_FORSAKRING, 100),
    ("moderna försäkring", CAT_FORSAKRING, 100),
    ("verisure", CAT_FORSAKRING, 100),
    ("sector alarm", CAT_FORSAKRING, 100),
    ("folktandvård", CAT_HALSA_HYGIEN, 100),
    # Lån
    ("csn ", CAT_LAN, 100),
    ("csn återbetalning", CAT_LAN, 100),
    ("volkswagen f", CAT_LAN, 90),
    ("billån", CAT_LAN, 100),
    ("santander", CAT_LAN, 80),
    # Hälsa & hygien
    ("apoteket", CAT_HALSA_HYGIEN, 100),
    ("apotek hjärtat", CAT_HALSA_HYGIEN, 100),
    ("hälsocentralen", CAT_HALSA_HYGIEN, 100),
    ("vårdcentral", CAT_HALSA_HYGIEN, 100),
    ("tandvård", CAT_HALSA_HYGIEN, 100),
    ("frisktandv", CAT_HALSA_HYGIEN, 100),
    ("1177", CAT_HALSA_HYGIEN, 100),
    ("yogiboost", CAT_HALSA_HYGIEN, 100),
    ("crossfit", CAT_HALSA_HYGIEN, 90),
    ("friskis", CAT_HALSA_HYGIEN, 100),
    ("puls & träning", CAT_HALSA_HYGIEN, 100),
    ("optihealth", CAT_HALSA_HYGIEN, 100),
    ("life ", CAT_HALSA_HYGIEN, 70),
    ("lyko", CAT_HALSA_HYGIEN, 100),
    # Nöje & fritid
    ("sf bio", CAT_NOJE_FRITID, 100),
    ("filmstaden", CAT_NOJE_FRITID, 100),
    ("biljetter", CAT_NOJE_FRITID, 80),
    ("tickster", CAT_NOJE_FRITID, 100),
    ("nordicchoice", CAT_NOJE_FRITID, 90),
    ("hemmakväll", CAT_NOJE_FRITID, 100),
    ("akademibokhandeln", CAT_NOJE_FRITID, 100),
    ("bokus", CAT_NOJE_FRITID, 100),
    ("adlibris", CAT_NOJE_FRITID, 100),
    ("steam", CAT_NOJE_FRITID, 100),
    ("playstation", CAT_NOJE_FRITID, 100),
    ("xbox", CAT_NOJE_FRITID, 100),
    ("nintendo", CAT_NOJE_FRITID, 100),
    ("lekia", CAT_NOJE_FRITID, 100),
    # Transport
    ("sl-kort", CAT_TRANSPORT, 100),
    ("sl ab", CAT_TRANSPORT, 100),
    ("västtrafik", CAT_TRANSPORT, 100),
    ("skånetrafiken", CAT_TRANSPORT, 100),
    ("circle k", CAT_TRANSPORT, 100),
    ("preem", CAT_TRANSPORT, 100),
    ("okq8", CAT_TRANSPORT, 100),
    ("st1", CAT_TRANSPORT, 100),
    ("ingo", CAT_TRANSPORT, 100),
    ("trängselskatt", CAT_TRANSPORT, 100),
    ("parkman", CAT_TRANSPORT, 100),
    ("q-park", CAT_TRANSPORT, 100),
    ("p-bolaget", CAT_TRANSPORT, 100),
    ("bolt", CAT_TRANSPORT, 100),
    ("voi", CAT_TRANSPORT, 100),
    ("taxi", CAT_TRANSPORT, 80),
    ("uber", CAT_TRANSPORT, 80),
    # Förbrukningsvaror
    ("rusta", CAT_FORBRUKNINGSVAROR, 100),
    ("clas ohlson", CAT_FORBRUKNINGSVAROR, 100),
    ("normal ", CAT_FORBRUKNINGSVAROR, 90),
    ("dollarstore", CAT_FORBRUKNINGSVAROR, 100),
    ("søstrene", CAT_FORBRUKNINGSVAROR, 100),
    ("sostrene", CAT_FORBRUKNINGSVAROR, 100),
    ("temu.com", CAT_FORBRUKNINGSVAROR, 100),
    ("temu", CAT_FORBRUKNINGSVAROR, 90),
    ("wish.com", CAT_FORBRUKNINGSVAROR, 100),
    ("aliexpress", CAT_FORBRUKNINGSVAROR, 90),
    ("ebay", CAT_FORBRUKNINGSVAROR, 80),
    # Hemutrustning
    ("ikea", CAT_HEMUTRUSTNING, 100),
    ("jysk", CAT_HEMUTRUSTNING, 100),
    ("ilva", CAT_HEMUTRUSTNING, 100),
    ("mio möbler", CAT_HEMUTRUSTNING, 100),
    ("hem & hobby", CAT_HEMUTRUSTNING, 100),
    ("hem och hobby", CAT_HEMUTRUSTNING, 100),
    ("soltorget", CAT_HEMUTRUSTNING, 80),
    ("panduro", CAT_HEMUTRUSTNING, 100),
    ("granngård", CAT_HEMUTRUSTNING, 100),
    ("granngarden", CAT_HEMUTRUSTNING, 100),
    ("elon", CAT_HEMUTRUSTNING, 100),
    ("inet ab", CAT_HEMUTRUSTNING, 100),
    ("inet.se", CAT_HEMUTRUSTNING, 100),
    (" inet ", CAT_HEMUTRUSTNING, 90),
    # Pension / sparande
    ("nordea liv", CAT_PENSION, 90),
    ("amf pension", CAT_PENSION, 90),
    ("skandia liv", CAT_PENSION, 90),
    ("isk-insättning", CAT_SPARMAL, 100),
    ("fondköp", CAT_SPARMAL, 100),
    ("aktieköp", CAT_SPARMAL, 100),
    ("avanza", CAT_SPARMAL, 80),
    ("nordnet", CAT_SPARMAL, 80),
    # Inkomst
    ("lön", CAT_LON, 100),
    ("inkab", CAT_LON, 90),
    ("försäkringskassan", CAT_OVRIG_INKOMST, 90),
    ("fkassa", CAT_OVRIG_INKOMST, 90),
    ("utlandsinsättning", CAT_OVRIG_INKOMST, 70),
    ("skatteverket", CAT_SKATTEATERBARING, 100),
    # Övrigt (fallback för obekanta)
    ("klarna", CAT_OVRIGT, 80),
    ("frisör", CAT_OVRIGT, 80),
    ("salong", CAT_OVRIGT, 70),
    ("unionen", CAT_OVRIGT, 90),
    ("saco", CAT_OVRIGT, 90),
    ("tco ", CAT_OVRIGT, 90),
    ("a-kassa", CAT_OVRIGT, 100),
    ("akassa", CAT_OVRIGT, 100),
    ("ränta", CAT_OVRIGT, 60),
    ("faktureringsavgift", CAT_OVRIGT, 100),
    ("snusbolag", CAT_OVRIGT, 100),
    ("snuslagret", CAT_OVRIGT, 100),
    ("tf bank", CAT_OVRIGT, 90),
    ("hjo kommun", CAT_BOENDE, 100),
    (" kommun", CAT_BOENDE, 80),
    ("avfall", CAT_BOENDE, 80),
]
