"""Svenska default-kategorier och basregler för kategorisering."""

DEFAULT_CATEGORIES: list[tuple[str, str | None, str | None]] = [
    # (name, parent_name, icon)
    ("Inkomst", None, "arrow-down"),
    ("Lön", "Inkomst", None),
    ("Swish in", "Inkomst", None),
    ("Återbetalning", "Inkomst", None),
    ("Swish ut", None, "arrow-up-right"),
    ("Boende", None, "home"),
    ("Bolåneränta", "Boende", None),
    ("Amortering", "Boende", None),
    ("Hyra", "Boende", None),
    ("El", "Boende", None),
    ("Internet", "Boende", None),
    ("Hemförsäkring", "Boende", None),
    ("Vatten/Avgift", "Boende", None),
    ("Mat", None, "shopping-cart"),
    ("Livsmedel", "Mat", None),
    ("Restaurang", "Mat", None),
    ("Café", "Mat", None),
    ("Take-away", "Mat", None),
    ("Transport", None, "car"),
    ("Kollektivtrafik", "Transport", None),
    ("Drivmedel", "Transport", None),
    ("Parkering", "Transport", None),
    ("Bilservice", "Transport", None),
    ("Taxi/Uber", "Transport", None),
    ("Nöje", None, "film"),
    ("Streaming", "Nöje", None),
    ("Biograf/Konsert", "Nöje", None),
    ("Spel", "Nöje", None),
    ("Böcker/Media", "Nöje", None),
    ("Hälsa", None, "heart"),
    ("Apotek", "Hälsa", None),
    ("Sjukvård", "Hälsa", None),
    ("Träning/Gym", "Hälsa", None),
    ("Kläder & Skor", None, "shirt"),
    ("Barn", None, "baby"),
    ("Förskola/Skola", "Barn", None),
    ("Leksaker", "Barn", None),
    ("Kläder barn", "Barn", None),
    ("Resor", None, "plane"),
    ("Flyg", "Resor", None),
    ("Hotell", "Resor", None),
    ("Semester", "Resor", None),
    ("Prenumerationer", None, "repeat"),
    ("Mobil", "Prenumerationer", None),
    ("Hemelektronik", None, None),
    ("Hem & Hushåll", None, "package"),
    ("Presenter", None, "gift"),
    ("Sparande/Investering", None, "trending-up"),
    ("ISK-insättning", "Sparande/Investering", None),
    ("Fondköp", "Sparande/Investering", None),
    ("Aktieköp", "Sparande/Investering", None),
    ("Pension", "Sparande/Investering", None),
    ("Överföring", None, "exchange"),
    ("Kontantuttag", None, "dollar-sign"),
    ("Avgifter & Ränta", None, "percent"),
    ("Skatt", None, "clipboard"),
    ("Försäkring", None, "shield"),
    ("Bilförsäkring", "Försäkring", None),
    ("Livförsäkring", "Försäkring", None),
    ("Övrigt", None, "help-circle"),
]


SEED_RULES: list[tuple[str, str, int]] = [
    # (pattern_substring_lowercase, category_name, priority)
    # Livsmedel
    ("ica ", "Livsmedel", 100),
    ("coop", "Livsmedel", 100),
    ("willys", "Livsmedel", 100),
    ("lidl", "Livsmedel", 100),
    ("hemköp", "Livsmedel", 100),
    ("city gross", "Livsmedel", 100),
    ("mathem", "Livsmedel", 100),
    # Restaurang / Café
    ("mcdonald", "Restaurang", 100),
    ("max ", "Restaurang", 100),
    ("burger king", "Restaurang", 100),
    ("sushi", "Restaurang", 100),
    ("pizza", "Restaurang", 100),
    ("espresso house", "Café", 100),
    ("wayne", "Café", 100),
    ("foodora", "Take-away", 100),
    ("wolt", "Take-away", 100),
    # Transport
    ("sl ab", "Kollektivtrafik", 100),
    ("storstockholms lokaltrafik", "Kollektivtrafik", 100),
    ("sj ab", "Kollektivtrafik", 100),
    ("västtrafik", "Kollektivtrafik", 100),
    ("skånetrafiken", "Kollektivtrafik", 100),
    ("circle k", "Drivmedel", 100),
    ("okq8", "Drivmedel", 100),
    ("preem", "Drivmedel", 100),
    ("ingo", "Drivmedel", 100),
    ("shell", "Drivmedel", 100),
    ("st1", "Drivmedel", 100),
    ("uber", "Taxi/Uber", 100),
    ("bolt.eu", "Taxi/Uber", 100),
    ("taxi stockholm", "Taxi/Uber", 100),
    ("easypark", "Parkering", 100),
    ("parkster", "Parkering", 100),
    # Streaming / Nöje
    ("netflix", "Streaming", 100),
    ("spotify", "Streaming", 100),
    ("hbo max", "Streaming", 100),
    ("viaplay", "Streaming", 100),
    ("disney+", "Streaming", 100),
    ("apple.com/bill", "Streaming", 90),
    ("steamgames", "Spel", 100),
    ("playstation", "Spel", 100),
    # Hälsa
    ("apotek hjärtat", "Apotek", 100),
    ("apotea", "Apotek", 100),
    ("kronans apotek", "Apotek", 100),
    ("sats", "Träning/Gym", 100),
    ("nordic wellness", "Träning/Gym", 100),
    # Telekom / Internet
    ("telia", "Mobil", 100),
    ("telenor", "Mobil", 100),
    ("hallon", "Mobil", 100),
    ("tre ", "Mobil", 100),
    ("comviq", "Mobil", 100),
    ("bahnhof", "Internet", 100),
    # El
    ("vattenfall", "El", 100),
    ("fortum", "El", 100),
    ("eon ", "El", 100),
    # Försäkring
    ("länsförsäkringar", "Hemförsäkring", 90),
    ("folksam", "Hemförsäkring", 90),
    ("if skadeförsäkring", "Hemförsäkring", 90),
    ("trygg-hansa", "Hemförsäkring", 90),
    # Swish — specific phrasings so incoming ≠ outgoing
    ("swish inbetalning", "Swish in", 110),
    ("swish betalning", "Swish ut", 110),
    # Lön
    ("lön", "Lön", 80),
    ("salary", "Lön", 80),
    # ISK / Invest
    ("isk", "ISK-insättning", 80),
    ("avanza", "Fondköp", 70),
    ("nordnet", "Fondköp", 70),
    # Kläder
    ("h&m", "Kläder & Skor", 100),
    ("zara", "Kläder & Skor", 100),
    ("lindex", "Kläder & Skor", 100),
    ("kappahl", "Kläder & Skor", 100),
    # Hem
    ("ikea", "Hem & Hushåll", 100),
    ("clas ohlson", "Hem & Hushåll", 100),
    ("jula", "Hem & Hushåll", 100),
    ("byggmax", "Hem & Hushåll", 100),
    ("bauhaus", "Hem & Hushåll", 100),
    # Elektronik
    ("netonnet", "Hemelektronik", 100),
    ("elgiganten", "Hemelektronik", 100),
    ("kjell", "Hemelektronik", 100),
    ("webhallen", "Hemelektronik", 100),
    # Barn
    ("babyshop", "Kläder barn", 100),
    ("lekia", "Leksaker", 100),
    # Resor
    ("sas ", "Flyg", 100),
    ("norwegian", "Flyg", 100),
    ("ryanair", "Flyg", 100),
    ("booking.com", "Hotell", 100),
    ("airbnb", "Hotell", 100),
    # Kontant / avgift
    ("bankomat", "Kontantuttag", 100),
    ("uttagsavgift", "Avgifter & Ränta", 100),
    ("ränta", "Avgifter & Ränta", 60),
    # Bolåneränta / Amortering
    ("bolåneränta", "Bolåneränta", 100),
    ("amortering", "Amortering", 100),
]
