"""Idempotent seed för EventTemplate-mallarna.

Mål V2: ~80 events över alla kategorier för pedagogisk variation.
Den här filen växer commit för commit — börjar med ~20 i fas 2/4 och
fylls på i fas 2/2 till 80.

Triggers-format (JSON):
- weekday: [4,5] = bara fredag/lördag
- month_day_min/max: 25-31 = bara mot månadsslutet
- reactive: "low_savings_buffer" | "high_balance" | etc.
- random_weight: 1.0 (default), högre = oftare
- season: "summer" | "christmas" | etc.
"""
from __future__ import annotations

from sqlalchemy.orm import Session

from .event_models import EventTemplate


# Skelett-uppsättning för fas 2/4 — ~20 events. Fylls på till 80 i 2/2.
EVENT_TEMPLATES: list[dict] = [
    # --- SOCIAL ---
    {
        "code": "bio_filmstaden",
        "title": "Bio på Filmstaden",
        "description": "Anna och Karim har bjudit dig på den nya storfilmen på Filmstaden Söndergatan på fredag.",
        "category": "social",
        "brand": "Filmstaden",
        "cost_min": 150, "cost_max": 200,
        "impact_social": 3, "impact_leisure": 2,
        "duration_days": 5,
        "triggers": {"weekday": [4, 5], "random_weight": 1.0},
        "social_invite_allowed": True,
    },
    {
        "code": "vapiano_pasta",
        "title": "Pasta på Vapiano",
        "description": "Två kompisar vill äta pasta efter jobbet. Vapiano vid Sergels torg.",
        "category": "social",
        "brand": "Vapiano",
        "cost_min": 220, "cost_max": 320,
        "impact_social": 4, "impact_leisure": 1,
        "duration_days": 3,
        "triggers": {"weekday": [3, 4], "random_weight": 1.0},
        "social_invite_allowed": True,
    },
    {
        "code": "karaoke_friday",
        "title": "Karaoke på Friday Bar",
        "description": "Klassen ska sjunga karaoke i fredag kväll. Kostar minst 350 kr för entré och drinkar.",
        "category": "social",
        "brand": "Friday Bar",
        "cost_min": 300, "cost_max": 450,
        "impact_social": 5, "impact_leisure": 3,
        "duration_days": 4,
        "triggers": {"weekday": [4], "random_weight": 0.8},
        "social_invite_allowed": True,
    },

    # --- SPORT ---
    {
        "code": "aik_match",
        "title": "AIK–Hammarby på Tele2 Arena",
        "description": "Stockholmsderby på fredag kväll! Biljettpris 450 kr. Korv och dryck inkluderat lite till.",
        "category": "sport",
        "brand": "AIK Fotboll",
        "cost_min": 400, "cost_max": 550,
        "impact_social": 5, "impact_leisure": 5,
        "duration_days": 7,
        "triggers": {"random_weight": 0.7},
        "social_invite_allowed": True,
    },
    {
        "code": "stockholm_marathon",
        "title": "Stockholm Marathon-anmälan",
        "description": "Anmälan stänger nästa vecka — om du betalar 600 kr nu får du sista platsen.",
        "category": "sport",
        "brand": "Stockholm Marathon",
        "cost_min": 600, "cost_max": 600,
        "impact_health": 6, "impact_social": 3,
        "duration_days": 7,
        "triggers": {"random_weight": 0.4, "season": "spring"},
        "social_invite_allowed": False,
    },

    # --- KULTUR ---
    {
        "code": "musikal_mamma_mia",
        "title": "Musikalen Mamma Mia på Cirkus",
        "description": "Mamma Mia-uppsättningen kommer till Stockholm. Biljett från 800 kr.",
        "category": "culture",
        "brand": "Cirkus",
        "cost_min": 800, "cost_max": 1100,
        "impact_social": 4, "impact_leisure": 5,
        "duration_days": 14,
        "triggers": {"random_weight": 0.3},
        "social_invite_allowed": True,
    },
    {
        "code": "spelmuseum",
        "title": "Spelmuseum med en kompis",
        "description": "En kompis vill gå till Spelmuseum vid Slussen — kostar 150 kr inträde.",
        "category": "culture",
        "brand": "Spelmuseum",
        "cost_min": 120, "cost_max": 180,
        "impact_social": 3, "impact_leisure": 2,
        "duration_days": 14,
        "triggers": {"random_weight": 0.6},
        "social_invite_allowed": True,
    },

    # --- FAMILY ---
    {
        "code": "mormor_kalas",
        "title": "Mormors 80-årskalas",
        "description": "Mormor fyller 80 nästa månad — du behöver köpa en present (förslag 500 kr).",
        "category": "family",
        "brand": None,
        "cost_min": 400, "cost_max": 700,
        "impact_social": 5, "impact_safety": 2,
        "duration_days": 14,
        "triggers": {"random_weight": 0.4},
        "social_invite_allowed": False,
    },
    {
        "code": "syskon_fodelsedag",
        "title": "Syskonets födelsedag",
        "description": "Ditt syskon fyller år nästa vecka — present på ungefär 350 kr räcker bra.",
        "category": "family",
        "brand": None,
        "cost_min": 250, "cost_max": 500,
        "impact_social": 3,
        "duration_days": 7,
        "triggers": {"random_weight": 0.5},
        "social_invite_allowed": False,
    },
    {
        "code": "familj_helg_gotland",
        "title": "Familjesemester en helg på Gotland",
        "description": "Föräldrarna föreslår en helg på Gotland. Du står för dina egna 1 200 kr.",
        "category": "family",
        "brand": None,
        "cost_min": 1100, "cost_max": 1400,
        "impact_social": 6, "impact_leisure": 6,
        "duration_days": 21,
        "triggers": {"random_weight": 0.3, "season": "summer"},
        "social_invite_allowed": False,
    },

    # --- UNEXPECTED (oförutsedda — inte declinable) ---
    {
        "code": "tandlakare_akut",
        "title": "Akut visdomstand",
        "description": "Du har fått en akut tandvärk. Tandläkaren sätter igång genast — 2 800 kr för ingreppet.",
        "category": "unexpected",
        "brand": None,
        "cost_min": 2500, "cost_max": 3200,
        "impact_safety": -2, "impact_health": -1,
        "duration_days": 1,
        "triggers": {"random_weight": 0.2},
        "social_invite_allowed": False,
        "declinable": False,
    },
    {
        "code": "diskmaskin_trasig",
        "title": "Diskmaskinen går sönder",
        "description": "Diskmaskinen läcker vatten — reparationen kostar 4 500 kr.",
        "category": "unexpected",
        "brand": None,
        "cost_min": 4000, "cost_max": 5500,
        "impact_safety": -3,
        "duration_days": 1,
        "triggers": {"random_weight": 0.15},
        "social_invite_allowed": False,
        "declinable": False,
    },
    {
        "code": "cykel_dack",
        "title": "Cykeln punktade",
        "description": "Cykeldäcket punktade på vägen hem. Servicebesök kostar 350 kr.",
        "category": "unexpected",
        "brand": None,
        "cost_min": 250, "cost_max": 500,
        "impact_economy": -1,
        "duration_days": 1,
        "triggers": {"random_weight": 0.4},
        "social_invite_allowed": False,
        "declinable": False,
    },

    # --- OPPORTUNITY ---
    {
        "code": "rea_volt_cykel",
        "title": "Rea på Volt-elcykeln du tittat på",
        "description": "Den elcykel du har följt är på rea — 4 500 kr istället för 7 000. Sluttid 3 dagar.",
        "category": "opportunity",
        "brand": "Volt",
        "cost_min": 4500, "cost_max": 4500,
        "impact_economy": -2, "impact_leisure": 4, "impact_health": 2,
        "duration_days": 3,
        "triggers": {"random_weight": 0.2},
        "social_invite_allowed": False,
    },
    {
        "code": "kompis_saljer_soffa",
        "title": "Kompis säljer sin gamla soffa",
        "description": "En kompis flyttar och vill bli av med sin soffa — 800 kr om du hämtar.",
        "category": "opportunity",
        "brand": None,
        "cost_min": 600, "cost_max": 1000,
        "impact_safety": 1, "impact_economy": -1,
        "duration_days": 5,
        "triggers": {"random_weight": 0.3},
        "social_invite_allowed": False,
    },

    # --- MAT ---
    {
        "code": "foodora_torsdag",
        "title": "Foodora-leverans en torsdag",
        "description": "Du orkar inte laga middag — 220 kr för en pasta från grillen.",
        "category": "mat",
        "brand": "Foodora",
        "cost_min": 180, "cost_max": 280,
        "impact_economy": -1, "impact_leisure": 1,
        "duration_days": 1,
        "triggers": {"weekday": [3], "random_weight": 0.6},
        "social_invite_allowed": False,
    },
    {
        "code": "espresso_house",
        "title": "Fika på Espresso House",
        "description": "Lunch utan att laga själv — 95 kr för dagens lunch på Espresso House.",
        "category": "mat",
        "brand": "Espresso House",
        "cost_min": 80, "cost_max": 130,
        "impact_economy": -0, "impact_leisure": 1,
        "duration_days": 1,
        "triggers": {"weekday": [1, 2], "random_weight": 0.5},
        "social_invite_allowed": True,
    },

    # --- LIFESTYLE ---
    {
        "code": "frisor_klippning",
        "title": "Klippning hos frisören",
        "description": "Det är dags att klippa sig — 450 kr på Stadsmissionen.",
        "category": "lifestyle",
        "brand": None,
        "cost_min": 350, "cost_max": 600,
        "impact_health": 1,
        "duration_days": 14,
        "triggers": {"random_weight": 0.3},
        "social_invite_allowed": False,
    },
    {
        "code": "spotify_premium",
        "title": "Spotify Premium fortsätter",
        "description": "Din Spotify Premium-prenumeration förnyas — 119 kr/mån.",
        "category": "lifestyle",
        "brand": "Spotify",
        "cost_min": 119, "cost_max": 119,
        "impact_leisure": 1,
        "duration_days": 1,
        "triggers": {"month_day_min": 1, "month_day_max": 5},
        "social_invite_allowed": False,
        "declinable": True,  # Eleven kan säga upp
    },

    # --- Sub-fas 2/2a: 20 fler events (totalt 40) ---

    # SOCIAL (mer variation)
    {
        "code": "pubrunda_södermalm",
        "title": "Pubrunda på Södermalm",
        "description": "Klassen drar runt på 3 ölhak i fredag kväll. Räkna med 500 kr.",
        "category": "social",
        "brand": None,
        "cost_min": 400, "cost_max": 700,
        "impact_social": 5, "impact_leisure": 3,
        "duration_days": 4,
        "triggers": {"weekday": [4], "random_weight": 0.6},
        "social_invite_allowed": True,
    },
    {
        "code": "brunch_urban_deli",
        "title": "Söndagsbrunch på Urban Deli",
        "description": "En kompis föreslår brunch på Urban Deli — 285 kr för buffé.",
        "category": "social",
        "brand": "Urban Deli",
        "cost_min": 250, "cost_max": 320,
        "impact_social": 4, "impact_leisure": 2,
        "duration_days": 4,
        "triggers": {"weekday": [6], "random_weight": 0.7},
        "social_invite_allowed": True,
    },
    {
        "code": "padel_central",
        "title": "Padel med klassen",
        "description": "Bana bokad på Padel Central nästa torsdag — 200 kr per spelare.",
        "category": "sport",
        "brand": "Padel Central",
        "cost_min": 180, "cost_max": 260,
        "impact_health": 3, "impact_social": 4, "impact_leisure": 2,
        "duration_days": 5,
        "triggers": {"random_weight": 0.7},
        "social_invite_allowed": True,
    },
    {
        "code": "bowling_bowlhuset",
        "title": "Bowling på Bowlhuset",
        "description": "Klasskvällen i fredag — bowling + pizza, 240 kr per person.",
        "category": "social",
        "brand": "Bowlhuset",
        "cost_min": 200, "cost_max": 280,
        "impact_social": 4, "impact_leisure": 3,
        "duration_days": 5,
        "triggers": {"weekday": [4, 5], "random_weight": 0.5},
        "social_invite_allowed": True,
    },
    {
        "code": "klättring_klättercentret",
        "title": "Klättring på Klättercentret",
        "description": "En kompis vill testa klättring — 220 kr inträde + skor.",
        "category": "sport",
        "brand": "Klättercentret",
        "cost_min": 180, "cost_max": 280,
        "impact_health": 4, "impact_leisure": 3, "impact_social": 2,
        "duration_days": 7,
        "triggers": {"random_weight": 0.4},
        "social_invite_allowed": True,
    },
    {
        "code": "way_out_west",
        "title": "Way Out West-festival",
        "description": "Festivalbiljett i Göteborg — 2 200 kr för 3-dagarspass.",
        "category": "culture",
        "brand": "Way Out West",
        "cost_min": 2000, "cost_max": 2500,
        "impact_social": 6, "impact_leisure": 6,
        "duration_days": 30,
        "triggers": {"random_weight": 0.2, "season": "summer"},
        "social_invite_allowed": True,
    },

    # CULTURE / KONSERT
    {
        "code": "konsert_avicii_arena",
        "title": "Konsert på Avicii Arena",
        "description": "En internationell artist spelar på Avicii Arena. Biljett 750 kr.",
        "category": "culture",
        "brand": "Avicii Arena",
        "cost_min": 600, "cost_max": 950,
        "impact_social": 4, "impact_leisure": 5,
        "duration_days": 14,
        "triggers": {"random_weight": 0.3},
        "social_invite_allowed": True,
    },
    {
        "code": "fotografiska",
        "title": "Utställning på Fotografiska",
        "description": "Ny utställning öppnad — inträde 195 kr. Stannar i 14 dagar till.",
        "category": "culture",
        "brand": "Fotografiska",
        "cost_min": 150, "cost_max": 220,
        "impact_leisure": 3, "impact_social": 1,
        "duration_days": 14,
        "triggers": {"random_weight": 0.5},
        "social_invite_allowed": True,
    },

    # OPPORTUNITY
    {
        "code": "black_friday_dator",
        "title": "Black Friday — bärbar dator",
        "description": "Dator du tittat på är 30% rabatt — 8 500 kr istället för 12 000. Slut på söndag.",
        "category": "opportunity",
        "brand": None,
        "cost_min": 8500, "cost_max": 8500,
        "impact_economy": -3, "impact_leisure": 2,
        "duration_days": 3,
        "triggers": {"random_weight": 0.15, "season": "november"},
        "social_invite_allowed": False,
    },
    {
        "code": "extratimmar_jobb",
        "title": "Extra timmar på jobbet",
        "description": "Chefen frågar om du kan ta 8 extra timmar i helgen — ger ~2 000 kr extra.",
        "category": "opportunity",
        "brand": None,
        "cost_min": 0, "cost_max": 0,  # Detta GER pengar — hanteras specialfall
        "impact_economy": 5, "impact_health": -2, "impact_social": -2, "impact_leisure": -1,
        "duration_days": 3,
        "triggers": {"random_weight": 0.4},
        "social_invite_allowed": False,
    },

    # UNEXPECTED (oförutsedda)
    {
        "code": "glasogon_trasiga",
        "title": "Glasögonen gick sönder",
        "description": "Bågen knäcktes — nya glasögon kostar 1 800 kr.",
        "category": "unexpected",
        "brand": None,
        "cost_min": 1500, "cost_max": 2400,
        "impact_safety": -1,
        "duration_days": 1,
        "triggers": {"random_weight": 0.15},
        "social_invite_allowed": False,
        "declinable": False,
    },
    {
        "code": "telefon_skarm",
        "title": "Telefonens skärm spräckt",
        "description": "Skärmreparation kostar 1 400 kr.",
        "category": "unexpected",
        "brand": None,
        "cost_min": 1200, "cost_max": 1900,
        "impact_safety": -1,
        "duration_days": 1,
        "triggers": {"random_weight": 0.2},
        "social_invite_allowed": False,
        "declinable": False,
    },
    {
        "code": "parkeringsavgift",
        "title": "Felparkeringsavgift",
        "description": "Du missade tidsskylten — bot på 800 kr.",
        "category": "unexpected",
        "brand": None,
        "cost_min": 600, "cost_max": 1000,
        "impact_economy": -1,
        "duration_days": 1,
        "triggers": {"random_weight": 0.1},
        "social_invite_allowed": False,
        "declinable": False,
    },
    {
        "code": "forkylning_apotek",
        "title": "Förkylning — apoteksrunda",
        "description": "Rejäl förkylning. Receptfria mediciner, halstabletter, vitaminer — 320 kr.",
        "category": "unexpected",
        "brand": None,
        "cost_min": 200, "cost_max": 450,
        "impact_health": -1,
        "duration_days": 1,
        "triggers": {"random_weight": 0.3, "season": "winter"},
        "social_invite_allowed": False,
        "declinable": False,
    },
    {
        "code": "cykel_stulen",
        "title": "Cykeln blev stulen",
        "description": "Vid pendeltåget — bom! Borta. Hemförsäkring täcker delvis (självrisk 1 500 kr).",
        "category": "unexpected",
        "brand": None,
        "cost_min": 1500, "cost_max": 1500,
        "impact_safety": -3, "impact_health": -1,
        "duration_days": 1,
        "triggers": {"random_weight": 0.05},
        "social_invite_allowed": False,
        "declinable": False,
    },

    # MAT
    {
        "code": "julbord_kollegorna",
        "title": "Julbord med kollegorna",
        "description": "Företagets julbord på Operaterrassen — 750 kr (egen del).",
        "category": "mat",
        "brand": "Operaterrassen",
        "cost_min": 600, "cost_max": 900,
        "impact_social": 4, "impact_leisure": 3,
        "duration_days": 7,
        "triggers": {"random_weight": 0.3, "season": "december"},
        "social_invite_allowed": False,
    },
    {
        "code": "fredagsmys_pizza",
        "title": "Fredagsmys-pizza från Pong",
        "description": "Pizza hem från Pong — 195 kr för en stor.",
        "category": "mat",
        "brand": "Pong",
        "cost_min": 150, "cost_max": 250,
        "impact_leisure": 1, "impact_social": 1,
        "duration_days": 1,
        "triggers": {"weekday": [4], "random_weight": 0.6},
        "social_invite_allowed": True,
    },

    # LIFESTYLE
    {
        "code": "gymkort_sats",
        "title": "Gymkort på SATS förnyas",
        "description": "12-månaders gymkort på SATS — 6 800 kr (eller månadsvis 599 kr).",
        "category": "lifestyle",
        "brand": "SATS",
        "cost_min": 599, "cost_max": 599,
        "impact_health": 4, "impact_leisure": 1,
        "duration_days": 7,
        "triggers": {"month_day_min": 1, "month_day_max": 5, "random_weight": 0.4},
        "social_invite_allowed": False,
    },
    {
        "code": "klader_hm_inkop",
        "title": "Säsongsskifte — kläder",
        "description": "Du behöver byta från höst- till vinterjacka. H&M, ungefär 950 kr.",
        "category": "lifestyle",
        "brand": "H&M",
        "cost_min": 700, "cost_max": 1400,
        "impact_health": 1, "impact_safety": 1,
        "duration_days": 14,
        "triggers": {"random_weight": 0.4, "season": "autumn"},
        "social_invite_allowed": False,
    },

    # --- Sub-fas 2/2b: 20 fler events (totalt 60) ---

    # SOCIAL
    {
        "code": "fodelsedagskalas_kompis",
        "title": "Födelsedagskalas hos en kompis",
        "description": "En kompis fyller år — kalas hemma med bidrag till mat 200 kr.",
        "category": "social",
        "brand": None,
        "cost_min": 150, "cost_max": 300,
        "impact_social": 4, "impact_leisure": 2,
        "duration_days": 7,
        "triggers": {"random_weight": 0.5},
        "social_invite_allowed": True,
    },
    {
        "code": "after_work_kollega",
        "title": "After work efter jobbet",
        "description": "En kollega bjuder med på AW. Drinkar 250 kr.",
        "category": "social",
        "brand": None,
        "cost_min": 200, "cost_max": 400,
        "impact_social": 3, "impact_leisure": 1,
        "duration_days": 2,
        "triggers": {"weekday": [3, 4], "random_weight": 0.6},
        "social_invite_allowed": True,
    },
    {
        "code": "kaffe_waynes",
        "title": "Kaffe på Wayne's Coffee",
        "description": "En kompis vill ses för en kopp — 65 kr för en latte.",
        "category": "social",
        "brand": "Wayne's Coffee",
        "cost_min": 50, "cost_max": 95,
        "impact_social": 2,
        "duration_days": 3,
        "triggers": {"random_weight": 0.7},
        "social_invite_allowed": True,
    },

    # FAMILY
    {
        "code": "foraldrar_guldbrollop",
        "title": "Föräldrarnas 50-årsdag som par",
        "description": "Stort firande — du går ihop med syskonen om en present på 800 kr.",
        "category": "family",
        "brand": None,
        "cost_min": 700, "cost_max": 1100,
        "impact_social": 5, "impact_safety": 2,
        "duration_days": 21,
        "triggers": {"random_weight": 0.2},
        "social_invite_allowed": False,
    },
    {
        "code": "kusin_examen",
        "title": "Kusins studentexamen",
        "description": "Kusinen tar studenten — du köper en blomma och ett kort, 250 kr.",
        "category": "family",
        "brand": None,
        "cost_min": 200, "cost_max": 400,
        "impact_social": 3,
        "duration_days": 14,
        "triggers": {"random_weight": 0.3, "season": "summer"},
        "social_invite_allowed": False,
    },

    # CULTURE
    {
        "code": "kungliga_operan",
        "title": "Föreställning på Kungliga Operan",
        "description": "En klassiker spelas — biljett 550 kr på balkongen.",
        "category": "culture",
        "brand": "Kungliga Operan",
        "cost_min": 450, "cost_max": 800,
        "impact_leisure": 4, "impact_social": 2,
        "duration_days": 14,
        "triggers": {"random_weight": 0.2},
        "social_invite_allowed": True,
    },
    {
        "code": "standup_norra_brunn",
        "title": "Stand-up på Norra Brunn",
        "description": "Komikerkväll med kompisar — 280 kr inträde.",
        "category": "culture",
        "brand": "Norra Brunn",
        "cost_min": 250, "cost_max": 350,
        "impact_social": 3, "impact_leisure": 4,
        "duration_days": 5,
        "triggers": {"random_weight": 0.4},
        "social_invite_allowed": True,
    },
    {
        "code": "stockholm_filmfestival",
        "title": "Stockholm Filmfestival-pass",
        "description": "Festivalpass för 5 filmer — 650 kr.",
        "category": "culture",
        "brand": "Stockholm Filmfestival",
        "cost_min": 600, "cost_max": 800,
        "impact_leisure": 5, "impact_social": 2,
        "duration_days": 14,
        "triggers": {"random_weight": 0.3, "season": "november"},
        "social_invite_allowed": True,
    },

    # SPORT
    {
        "code": "djurgarden_hockey",
        "title": "Djurgården-Frölunda i Hovet",
        "description": "Hockeymatch i Hovet — biljett 320 kr.",
        "category": "sport",
        "brand": "Djurgården Hockey",
        "cost_min": 280, "cost_max": 450,
        "impact_social": 4, "impact_leisure": 4,
        "duration_days": 7,
        "triggers": {"random_weight": 0.4, "season": "winter"},
        "social_invite_allowed": True,
    },
    {
        "code": "vasaloppet_anmalan",
        "title": "Vasaloppet-anmälan",
        "description": "Anmälningsavgift för Vasaloppet — 1 950 kr. Kräver hård träning men är en livsupplevelse.",
        "category": "sport",
        "brand": "Vasaloppet",
        "cost_min": 1900, "cost_max": 2200,
        "impact_health": 6, "impact_social": 2,
        "duration_days": 7,
        "triggers": {"random_weight": 0.15, "season": "autumn"},
        "social_invite_allowed": False,
    },
    {
        "code": "yoga_helg_kursgard",
        "title": "Yogahelg på Sigtunastiftelsen",
        "description": "Två-dagars yogaretreat — 2 400 kr inkl. mat och boende.",
        "category": "sport",
        "brand": "Sigtunastiftelsen",
        "cost_min": 2200, "cost_max": 2800,
        "impact_health": 5, "impact_safety": 2,
        "duration_days": 21,
        "triggers": {"random_weight": 0.15},
        "social_invite_allowed": False,
    },

    # OPPORTUNITY
    {
        "code": "blocket_cykel",
        "title": "Bra cykel på Blocket",
        "description": "En begagnad cykel som passar dig — 1 600 kr istället för 4 500 ny.",
        "category": "opportunity",
        "brand": "Blocket",
        "cost_min": 1500, "cost_max": 1800,
        "impact_health": 2, "impact_economy": -1,
        "duration_days": 2,
        "triggers": {"random_weight": 0.25},
        "social_invite_allowed": False,
    },
    {
        "code": "extrajobb_tutor",
        "title": "Erbjudande: läxhjälpsjobb",
        "description": "Familj söker läxhjälp 4 timmar/vecka — ger ~1 600 kr/mån.",
        "category": "opportunity",
        "brand": None,
        "cost_min": 0, "cost_max": 0,
        "impact_economy": 4, "impact_social": -1, "impact_leisure": -2,
        "duration_days": 7,
        "triggers": {"random_weight": 0.3},
        "social_invite_allowed": False,
    },
    {
        "code": "bonus_arbetsgivaren",
        "title": "Oförväntad bonus från jobbet",
        "description": "Arbetsgivaren delar ut en kvartalsbonus — 2 500 kr extra på lönen.",
        "category": "opportunity",
        "brand": None,
        "cost_min": 0, "cost_max": 0,
        "impact_economy": 5, "impact_safety": 2,
        "duration_days": 1,
        "triggers": {"random_weight": 0.1},
        "social_invite_allowed": False,
        "declinable": False,  # Bonus accepteras automatiskt
    },

    # UNEXPECTED
    {
        "code": "veterinar_kasus",
        "title": "Akut veterinärbesök",
        "description": "Husdjuret behöver akutvård — 3 200 kr.",
        "category": "unexpected",
        "brand": None,
        "cost_min": 2800, "cost_max": 4500,
        "impact_safety": -2, "impact_health": -1,
        "duration_days": 1,
        "triggers": {"random_weight": 0.1},
        "social_invite_allowed": False,
        "declinable": False,
    },
    {
        "code": "mobil_i_toa",
        "title": "Mobilen tappad i toa",
        "description": "Klassiker — vatten- och kommer aldrig tillbaka. Ny billig modell 2 800 kr.",
        "category": "unexpected",
        "brand": None,
        "cost_min": 2500, "cost_max": 4000,
        "impact_safety": -2,
        "duration_days": 1,
        "triggers": {"random_weight": 0.1},
        "social_invite_allowed": False,
        "declinable": False,
    },

    # MAT
    {
        "code": "sushi_yama_takeaway",
        "title": "Sushi från Yama",
        "description": "Du orkar inte laga — sushi för 240 kr.",
        "category": "mat",
        "brand": "Sushi Yama",
        "cost_min": 200, "cost_max": 320,
        "impact_leisure": 1,
        "duration_days": 1,
        "triggers": {"random_weight": 0.5},
        "social_invite_allowed": False,
    },
    {
        "code": "vegan_bistro",
        "title": "Vegansk middag på Mahalo",
        "description": "Du och en kompis testar Mahalo — 350 kr per person.",
        "category": "mat",
        "brand": "Mahalo",
        "cost_min": 300, "cost_max": 450,
        "impact_health": 2, "impact_social": 3,
        "duration_days": 5,
        "triggers": {"random_weight": 0.4},
        "social_invite_allowed": True,
    },

    # LIFESTYLE
    {
        "code": "hbo_max_pren",
        "title": "HBO Max-prenumeration",
        "description": "HBO Max — 109 kr/mån. Förnyas idag.",
        "category": "lifestyle",
        "brand": "HBO Max",
        "cost_min": 109, "cost_max": 109,
        "impact_leisure": 1,
        "duration_days": 1,
        "triggers": {"month_day_min": 5, "month_day_max": 10},
        "social_invite_allowed": False,
        "declinable": True,
    },
    {
        "code": "kontaktlinser_synsam",
        "title": "Nya kontaktlinser från Synsam",
        "description": "3-månaders förråd kontaktlinser — 1 100 kr.",
        "category": "lifestyle",
        "brand": "Synsam",
        "cost_min": 950, "cost_max": 1300,
        "impact_health": 1,
        "duration_days": 14,
        "triggers": {"random_weight": 0.25},
        "social_invite_allowed": False,
    },
]


def seed_event_templates(session: Session) -> int:
    """Idempotent seed — bara nya rader läggs till."""
    existing = {e.code for e in session.query(EventTemplate).all()}
    added = 0
    for tpl in EVENT_TEMPLATES:
        if tpl["code"] in existing:
            continue
        session.add(EventTemplate(
            code=tpl["code"],
            title=tpl["title"],
            description=tpl["description"],
            category=tpl["category"],
            brand=tpl.get("brand"),
            cost_min=tpl["cost_min"],
            cost_max=tpl["cost_max"],
            impact_economy=tpl.get("impact_economy", 0),
            impact_health=tpl.get("impact_health", 0),
            impact_social=tpl.get("impact_social", 0),
            impact_leisure=tpl.get("impact_leisure", 0),
            impact_safety=tpl.get("impact_safety", 0),
            duration_days=tpl.get("duration_days", 5),
            triggers=tpl.get("triggers"),
            social_invite_allowed=tpl.get("social_invite_allowed", False),
            declinable=tpl.get("declinable", True),
            ai_text_template=tpl.get("ai_text_template"),
        ))
        added += 1
    if added:
        session.flush()
    return added
